---
galaxy_info:
  role_name: mcp-operations
  namespace: mcp
  author: MCP Management System
  description: MCP server operations and command execution with fully externalized variables
  company: ""
  license: MIT
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  
  galaxy_tags:
    - mcp
    - operations
    - command
    - claude

dependencies: []