---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    # Default SSH configuration for dynamic hosts
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s"
    
    # Claude CLI command
    claude_cli_command: "claude"
    
    # MCP server settings
    mcp_server_command: "npx"
    mcp_server_args_prefix: "-y"
    
    # Enable/disable specific MCP servers
    mcp_servers_enabled:
      brave_search: true
      context7: true
      puppeteer: true
      desktop_commander: true
      sequential_thinking: true
      git: true
      github: true
      gitlab: true
      markitdown: true   # Available via uvx markitdown-mcp
      memory: true
      pandoc: true       # Available via uvx mcp-pandoc
      pdf_tools: false   # No package available yet
      ansible: false     # Use mcp-cli-adapter with ansible commands
      filesystem: true
      mcp_cli_adapter: true  # Available via uvx mcp-shell-server
      ssh: true
    
    # Disabled MCP servers (will be added to Claude's disabledMcpjsonServers list)
    # This prevents them from loading even if they exist in .mcp.json
    # mcp_disabled_servers:
    #   - ansible
    #   - pandoc