---
- name: Configure Claude Code MCP Servers
  hosts: localhost
  gather_facts: yes
  
  vars:
    # Default scope is user
    mcp_scope: "{{ scope | default('user') }}"
    # Project path is optional
    mcp_project_path: "{{ project_path | default('') }}"
    # Server selection mode: all, group, or individual
    mcp_mode: "{{ mode | default('all') }}"
    # Specific servers to configure (comma-separated)
    mcp_servers_list: "{{ servers | default('') }}"
    # Specific group to configure
    mcp_group: "{{ group | default('') }}"
    
  pre_tasks:
    - name: Load environment variables and configuration
      include_role:
        name: mcp-servers
        tasks_from: load-env
        
    - name: Validate scope
      fail:
        msg: "Invalid scope '{{ mcp_scope }}'. Must be 'user' or 'project'"
      when: mcp_scope not in ['user', 'project']
      
    - name: Validate project path for project scope
      fail:
        msg: "project_path is required when scope is 'project'"
      when: 
        - mcp_scope == 'project'
        - mcp_project_path == ''
      
    - name: Validate Claude Code installation
      command: which claude
      register: claude_check
      failed_when: claude_check.rc != 0
      changed_when: false
      
    - name: Get current list of MCP servers
      command: claude mcp list
      register: current_servers
      changed_when: false
      ignore_errors: true

  roles:
    - mcp-servers

  post_tasks:
    - name: Display configuration summary
      debug:
        msg: |
          Claude Code MCP servers configuration complete!
          
          Scope: {{ mcp_scope }}{% if mcp_scope == 'project' %} ({{ mcp_project_path }}){% endif %}
          Mode: {{ mcp_mode }}
          {% if mcp_mode == 'individual' %}
          Servers: {{ mcp_servers_list }}
          {% elif mcp_mode == 'group' %}
          Group: {{ mcp_group }}
          {% endif %}
          
          Configuration loaded from:
          - .env file: {{ (env_file_stat.stat.exists | default(false)) | ternary('Yes', 'No') }}
          - config.yml: {{ (config_file_stat.stat.exists | default(false)) | ternary('Yes', 'No') }}
          
          To verify configuration:
          {% if mcp_scope == 'user' %}
          claude mcp list -s user
          {% else %}
          cd {{ mcp_project_path }} && claude mcp list
          {% endif %}