---
- name: Set default env file path if not provided
  set_fact:
    mcp_env_file: "{{ mcp_env_file | default('.env') }}"

- name: Check for .env file
  stat:
    path: "{{ mcp_env_file }}"
  register: env_file_stat

- name: Read .env file content
  slurp:
    src: "{{ mcp_env_file }}"
  register: env_file_content
  when: env_file_stat.stat.exists

- name: Parse and set environment variables
  set_fact:
    mcp_parsed_env: "{{ mcp_parsed_env | default({}) | combine({item.split('=')[0]: item.split('=', 1)[1]}) }}"
  loop: "{{ (env_file_content.content | b64decode).splitlines() }}"
  when:
    - env_file_stat.stat.exists
    - item is match('^[A-Z_][A-Z0-9_]*=.*')
    - not item.startswith('#')
  no_log: true

- name: Check for config.yml file
  stat:
    path: "{{ playbook_dir }}/config.yml"
  register: config_file_stat

- name: Load variables from config.yml if exists
  include_vars: "{{ playbook_dir }}/config.yml"
  when: config_file_stat.stat.exists

- name: Debug loaded variables
  debug:
    msg: |
      Loaded environment variables: {{ mcp_parsed_env.keys() | list | length if mcp_parsed_env is defined else 0 }}
      Variables: {{ mcp_parsed_env.keys() | list | sort | join(', ') if mcp_parsed_env is defined else 'None' }}
  when: ansible_verbosity > 1