---
- name: Set default env file path if not provided
  set_fact:
    mcp_env_file: "{{ mcp_env_file | default('.env') }}"

- name: Check for .env file
  stat:
    path: "{{ mcp_env_file }}"
  register: env_file_stat

- name: Read .env file content
  slurp:
    src: "{{ mcp_env_file }}"
  register: env_file_content
  when: env_file_stat.stat.exists

- name: Parse and set environment variables
  set_fact:
    "{{ (item.split('=')[0] | lower) }}": "{{ item.split('=', 1)[1] }}"
  loop: "{{ (env_file_content.content | b64decode).splitlines() }}"
  when:
    - env_file_stat.stat.exists
    - item is match('^[A-Z_][A-Z0-9_]*=.*')
    - not item.startswith('#')
  no_log: true

- name: Check for config.yml file
  stat:
    path: "{{ playbook_dir }}/config.yml"
  register: config_file_stat

- name: Load variables from config.yml if exists
  include_vars: "{{ playbook_dir }}/config.yml"
  when: config_file_stat.stat.exists

- name: Debug loaded variables
  debug:
    msg: "Loaded vars: github_token={{ github_token | default('NOT SET') }}, brave_api_key={{ brave_api_key | default('NOT SET') }}, my_custom_var={{ my_custom_var | default('NOT SET') }}"
  when: ansible_verbosity > 1